name : WORKLOG

on:
    push:
        branches: [ "main" ]
        # Publish semver tags as releases.
        tags: [ 'v*.*.*' ]

# env : 
#     REGISTRY: ghcr.io
#     IMAGE_NAME: ${{ github.repository }}
jobs:
    UnitTest:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v3
        -   name: SetupRails
            uses: ruby/setup-ruby@v1
            with: 
                ruby-version: '3.3.1'
        -   name: Install dependencies
            run: |
                gem install bundler
                bundle install --jobs 4 --retry 3
        -   name: Database setup
            run: |
                bundle exec rails db:create
                bundle exec rails db:migrate
        -   name: Run tests
            run: bundle exec rails test
            # run: bundle exec rspec

    build:
        runs-on: ubuntu-latest
        needs: UnitTest
        steps:
        -   name: Checkout
            uses: actions/checkout@v3

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

        -   name: Build Docker image
            run: |
                docker buildx create --use
                docker buildx build -t peerodds/rubyonrails:latest
        -   name: Log in to Docker Hub
            uses: docker/login-action@v1
            with: 
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  
        -   name: Push Docker image
            run: docker push peerodds/rubyonrails:latest
    # deploy:
    #         runs-on: ubuntu-latest
        
    #         needs: build
        
    #         steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v2
        
    #         - name: Set up Ruby
    #           uses: ruby/setup-ruby@v1
    #           with:
    #             ruby-version: '3.3'
        
    #         - name: Install dependencies
    #           run: |
    #             gem install bundler -v 2.5.9
    #             bundle install
                
        


